dictionaries = ["en_us"]
words = [
    "CLI",
    "CME",
    "OHLC",
    "OHLCV",
    "SMA",
    "backtest",
    "backtester",
    "computables",
    "dataclass",
    "dataclasses",
    "instancecheck",
    "maxlen",
    "metaclass",
    "michal",
    "pnl",
    "pyrefly",
    "sitarz",
]
min_word_length = 3
