interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = ["src",]

[[modules ]]
path = "ataraxia.compute"
depends_on = ["ataraxia.errors"]

[[modules ]]
path = "ataraxia.provider"
depends_on = ["ataraxia.bar", "ataraxia.errors"]

[[modules ]]
path = "ataraxia.bar"
depends_on = []

[[modules ]]
path = "ataraxia.source"
depends_on = ["ataraxia.compute", "ataraxia.provider"]

[[modules ]]
path = "ataraxia.errors"
depends_on = []
utility = true

[[modules ]]
path = "ataraxia.cli"
depends_on = ["ataraxia.broker", "ataraxia.backtest"]

[[modules ]]
path = "ataraxia.util"
depends_on = ["ataraxia.compute", "ataraxia.errors"]
utility = true

[[modules ]]
path = "ataraxia.backtest"
depends_on = ["ataraxia.provider", "ataraxia.util", "ataraxia.compute", "ataraxia.broker", "ataraxia.errors", "ataraxia.source"]

[[modules ]]
path = "ataraxia.feature"
depends_on = ["ataraxia.errors", "ataraxia.bar", "ataraxia.compute"]

[[modules ]]
path = "ataraxia.broker"
depends_on = ["ataraxia.bar", "ataraxia.compute"]
